### ISSUE TITLE
Code incomplete??

### ISSUE THREAD

**Issue by suruthibalakrishnan** [sohyeon98720/face-recognition-by-OAGAN#20]
Is this code incomplete and does this code de occlude an  image

**Comment by sohyeon98720** [comment]
yes we had an issue with designing loss function and we are still working on it.
Also this is the variation of [Semi-Supervised Natural Face De-Occlusion](https://sci-hub.se/https://ieeexplore.ieee.org/abstract/document/9195444), so the loss function and the datasets are different from the original.

**Comment by suruthibalakrishnan** [comment]
hey do you have the code and dataset  or  do you know the link for the original version. I found this one https://github.com/swordcheng/OA-GAN but it doesn't have the dataset.
